### ISSUE TITLE
TypeError: repeat(): argument 'repeats' must be tuple of ints, but found element of type float at pos 2

### ISSUE THREAD

**Issue by e0xextazy** [neonbjb/DL-Art-School#3]
To reproduce: run `codes/models/audio/tts/unified_voice3.py`.

In:
```
ac_expansion_factor = mel_codes.shape[-1] / aligned_codes.shape[-1]
aligned_codes = aligned_codes.repeat(1, ac_expansion_factor)
```
`ac_expansion_factor = 0.4332 = 250 / 577` but should be `Int`

**Comment by e0xextazy** [comment]
i want to test solo model by random inputs

**Comment by neonbjb** [comment]
unified_voice3 is an experimental model that will probably be deleted. Assuming you are looking to train tortoise, you want unified_voice2.

**Comment by e0xextazy** [comment]
Thank you!
