### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1024 and 512x1024)

### ISSUE THREAD

**Issue by e0xextazy** [neonbjb/DL-Art-School#4]
To reproduce run `codes/models/clip/clvp.py`

**Comment by e0xextazy** [comment]
i want to test solo model by random inputs

**Comment by e0xextazy** [comment]
Or me need usage `text_voice_clip.py` for CLVP model in Tortoise?

**Comment by neonbjb** [comment]
Correct, the Tortoise CLVP model is text_voice_clip.
